import 'dart:ui';
import 'package:flutter/material.dart';

class EngLang {
  EngLang._();

  static const String Login = "Login";
  static const String mobilenumber = "Mobile number";
  static const String password = "Password";
  static const String forgotpassword = "Forgot password ?";
  static const String donthaveaccount = "Don't have account ?";
  static const String signup = "Sign Up";
  static const String signupheading = "SignUp";
  static const String name = "Name";
  static const String locality = "Locality & City";
  static const String renterpassword = "Re-enter Password";
  static const String sendotp = "Send OTP";
  static const String verifyotp = "Verify OTP";
  static const String verify = "Verify";
  static const String verifyText =
      "Please enter the 6 digit OTP that you received on mobile number";
  static const String verifyText2 = "";
  static const String enterotp = "Please Enter OTP";
  static const String plancategory = "Plan category";
  static const String twodplans = "2d plans";
  static const String threedplans = "3d plans";
  static const String apartment = "Apartment";
  static const String videos = "Videos";
  static const String seeall = "See all";
  static const String blogs = "Blogs";
  static const String home = "Home";
  static const String customize = "Customize";
  static const String myplans = "My Plans";
  static const String settings = "Settings";
  static const String searchplans = "Search Plans";
  static const String filter = "Filter";
  static const String filterremove = "Remove Filter";
  static const String area = "Area";
  static const String direction = "Direction";
  static const String floor = "Floor";
  static const String applyfilter = "Apply Filter";
  static const String widthheight = "WXL";
  static const String desfloor =
      "सभी प्लान जिनमें मंजिल G+1 के लिए प्लान शामिल है,फ़िल्टर होंगे।";
  static const String width = "Width";
  static const String length = "Length";
  static const String description = "Description";
  static const String viewdetail = "View Details";
  static const String clickfloordesc = "(Click on any floor to view plan)";
  static const String bedroom = "Bedrooms";
  static const String hall = "Halls";
  static const String kitchen = "Kitchens";
  static const String balcony = "Balcony";
  static const String bathroom = "Bathrooms";
  static const String floorplan = "Floor plan";
  static const String floorelevation = "Ground Floor Elevation";
  static const String buynow = "Buy Now";
  static const String groundfloor = "Ground Floor";
  static const String customizerequest = "Customise Request";
  static const String customisationdetail = "Customisation Details";
  static const String newlength = "New Length";
  static const String variation = "(variation of only +/- 15% can be made)";
  static const String currentlength = "Current length";
  static const String newwidth = "New Width";
  static const String currentwidth = "Current Width";
  static const String newarea = "New Area";
  static const String currentarea = "Current Area";
  static const String facingdirection = "Facing Direction";
  static const String currentdirection = "Current Direction";
  static const String planforfloor = "Plan for Floor";
  static const String currentfloors = "Current Floors";
  static const String elevationrequired = "Elevation Required";
  static const String calculateamount = "Calculate Amount";
  static const String elevation = "Elevation";
  static const String requestcall = "Request Call";
  static const String viewproduct = "View Product";
  static const String customiseplan = "Customise Plan";
  static const String customisationrequests = "Customisation Requests";
  static const String searchrequest = "Search Requests";
  static const String language = "Language";
  static const String total_amount = "Total Amount";
  static const String profile = "Profile";
  static const String aboutus = "About Us";
  static const String appinfo = "App Info";
  static const String transactiondetails = "Transaction Details";
  static const String privacypolicy = "Privacy Policy";
  static const String contactus = "Contact Us";
  static const String termscondition = "Terms & Condition";
  static const String helpsupport = "Help Support";
  static const String logout = "Logout";
  static const String buyplan = "Buy Plan";
  static const String planlist = "Plan list";
  static const String plandes =
      "All plans below the selected floor plan will automatically be considered as part of the purchase package for ex if you buy G+1 plan the plan for G will also be unlocked";
  static const String profilename = "Profile Name";
  static const String registernumber = "Registered Number";
  static const String createpassword = "Create Password";
  static const String address = "Address";
  static const String editprofilenmae = "Edit Profile Name";
  static const String chnagerregistrednumber = "Change Registered Number";
  static const String createnewpassword = "Create New Password";
  static const String editprofileaddress = "Edit Profile Address";
  static const String enterprofilename = "Enter Profile Name";
  static const String enterprofileaddress = "Enter Profile Address";
  static const String oldpassword = "Old Password";
  static const String newpassword = "New Password";
  static const String confirmpassword = "Confirm Password";
  static const String submit = "Submit";
  static const String transactions = "Transactions";
  static const String customise = "Customise";
  static const String totalpaymentamt = "Total paying Amount";
  static const String orederid = "Order Id";
  static const String paymentdate = "Payment Date";
  static const String referencenumber = "Reference Number";
  static const String plancost = "Plan Cost";
  static const String elevationcost = "Elevation Cost";
  static const String customisationsrequests = "Customisation Requests";
  static const String selectarea = "Select Area";
  static const String selectdirection = "Select Direction";
  static const String selectfloor = "Select Floor";
  static const String errormobilenumber = "Mobile Number can not be left blank";
  static const String errorpassword = "Password can not be left blank";
  static const String errorvalidmobileno = "Please enter valid Mobile Number";
  static const String errorname = "Name can not be left blank";
  static const String errorlocalitycity = "Locality & City can not be blank";
  static const String errorconfirmpassword =
      'Confirm Password can not be left blank';
  static const String errorpassconfirmPassword =
      'Password and Confirm Password should be same';
  static const String entermobilenumber = "Enter Mobile Number";
  static const String getotp = "Get OTP";
  static const String forgotpass = "FORGOT PASSWORD";
  static const String erroraddress = "Address can not br blank";
  static const String currentnothingtoshow =
      "Currently, there is nothing to show";
  static const String enterlength = "Please Enter Length";
  static const String errorlength = "Please enter valid length";
  static const String errorwidth = "Please enter valid width";
  static const String entyerwidth = "Please Enter width";
  static const String enterfacingdirection = "Please select Facing direction";
  static const String enterplanfloor = "Please select Plan Floor";
  static const String enterelevation = " Please select Elevation Required";
  static const String lengthbetween1 = "Please specify the Length between ";
  static const String to = " to ";
  static const String widthbetween1 = "Please specify the Width between ";
}

class HindiLang {
  HindiLang._();

  static const String Login = 'लॉगिन';
  static const String mobilenumber = "मोबाइल नंबर";
  static const String password = "पासवर्ड";
  static const String forgotpassword = "पासवर्ड भूल गए ?";
  static const String donthaveaccount = "खाता नहीं है ?";
  static const String signup = "साइन उप";
  static const String signupheading = "साइन उप";
  static const String name = "नाम";
  static const String locality = "लोकैलिटी शहर";
  static const String renterpassword = "पासवर्ड दोबारा एंटर करें";
  static const String sendotp = "ओटीपी भेजें";
  static const String verifyotp = "वेरीफाई OTP";
  static const String verifyText = "कृपया मोबाइल नंबर";
  static const String verifyText2 = "पर प्राप्त 6 अंकों का ओटीपी दर्ज करें";
  static const String enterotp = "कृपया ओटीपी दर्ज करें";
  static const String verify = "वेरीफाई";
  static const String plancategory = "प्लान केटेगरी";
  static const String twodplans = "2d plans";
  static const String threedplans = "3d plans";
  static const String apartment = "Apartment";
  static const String videos = "वीडियो";
  static const String seeall = "सभी देखें";
  static const String blogs = "ब्लॉग";
  static const String home = "होम";
  static const String customize = "कस्टमाइज";
  static const String myplans = "माय प्लान";
  static const String settings = "सेटिंग्स";
  static const String searchplans = "प्लान सर्च करें";
  static const String filter = "फ़िल्टर";
  static const String filterremove = "फ़िल्टर हटाएँ";
  static const String area = "एरिया";
  static const String direction = "दिशा";
  static const String floor = "फ्लोर के लिए प्लान";
  static const String applyfiltter = "अप्लाई फ़िल्टर";
  static const String widthheight = "चौxला";
  static const String floor1 = "फ्लोर";
  static const String desfloor =
      "सभी प्लान जिनमें मंजिल G+1 के लिए प्लान शामिल है,फ़िल्टर होंगे।";
  static const String width = "चौड़ाई";
  static const String length = "लम्बाई";
  static const String description = "डिस्क्रिप्शन";
  static const String viewdetail = "विवरण देखें";
  static const String clickfloordesc =
      "(प्लान देखने के लिए किसी भी फ्लोर पर क्लिक करें)";
  static const String bedroom = "बैडरूम";
  static const String hall = "हॉल";
  static const String kitchen = "किचन";
  static const String balcony = "बालकनी";
  static const String bathroom = "बाथरूम";
  static const String floorplan = "फ्लोर प्लान";
  static const String floorelevation = "फ्लोर एलिवेशन";
  static const String buynow = "खरीदें";
  static const String groundfloor = "Ground Floor";
  static const String customizerequest = "कस्टमाइज रिक्वेस्ट";
  static const String customisationdetail = "कस्टमाइज डीटेल";
  static const String newlength = "नई लंबाई";
  static const String variation = "(केवल +/- 15% का परिवर्तन कि या जा सकता है)";
  static const String currentlength = "वर्तमान लंबाई";
  static const String newwidth = "नई चौड़ाई";
  static const String currentwidth = "वर्तमान चौड़ाई";
  static const String newarea = "नया एरिया";
  static const String currentarea = "वर्तमान क्षेत्र";
  static const String facingdirection = "दिशा";
  static const String currentdirection = "वर्तमान दिशा";
  static const String planforfloor = "फ्लोर प्लान";
  static const String currentfloors = "वर्तमान फ्लोर";
  static const String elevationrequired = "एलिवेशन की आवशयकता";
  static const String calculateamount = "कैलकुलेट करें";
  static const String elevation = "एलिवेशन";
  static const String requestcall = "कॉल रिक्वेस्ट करें";
  static const String viewproduct = "प्रोडक्ट देखें";
  static const String customiseplan = "कस्टमाइज प्लान";
  static const String customisationrequests = "Customisation Requests";
  static const String searchrequest = " रिक्वेस्ट्स सर्च करें";
  static const String language = "भाषा";
  static const String total_amount = "टोटल अमाउंट";
  static const String profile = "प्रोफाइल";
  static const String aboutus = "अबाउट उस";
  static const String appinfo = "ऐप इन्फो";
  static const String transactiondetails = "ट्रांसेक्शन डिटेल्स";
  static const String privacypolicy = "प्राइवेसी पॉलिसी";
  static const String contactus = "कॉन्टेक्ट उस";
  static const String termscondition = "टर्म्स & कंडीशन";
  static const String helpsupport = "हेल्प सपोर्ट";
  static const String logout = "लॉगआउट";
  static const String buyplan = "प्लान खरीदें";
  static const String planlist = "प्लान लिसट";
  static const String plandes =
      "सेलेक्ट किए गए फ्लोर प्लान के नीचे की के सभी प्लान आपको सेलेक्ट किए गए प्लान के साथ अनलॉक हो जाएगा । उदाहरण के लिए यदि आप G+2 फ्लोर का प्लान लेते हैं तो आपको G+1 और G फ्लोर का प्लान भी साथ मिलेगा ।";
  static const String profilename = "प्रोफाइल नाम";
  static const String registernumber = "रजिस्टर्ड नंबर";
  static const String createpassword = "पासवर्ड";
  static const String address = "पता";
  static const String editprofilenmae = "एडिट प्रोफाइल नाम";
  static const String chnagerregistrednumber = " रजिस्टर्ड नंबर बदले";
  static const String createnewpassword = "नया पासवर्ड";
  static const String editprofileaddress = "एडिट प्रोफाइल पता";
  static const String enterprofilename = "एंटर प्रोफाइल नाम";
  static const String oldpassword = "पुराना पासवर्ड";
  static const String newpassword = "नया पासवर्ड";
  static const String enterprofileaddress = "एंटर प्रोफाइल पता";
  static const String confirmpassword = "पासवर्ड दोबारा एंटर करें";
  static const String submit = "सबमिट";
  static const String transactions = "ट्रांसक्शन्स";
  static const String customise = "कस्टमाइज";
  static const String totalpaymentamt = "टोटल भुकतान राशि";
  static const String orederid = "आर्डर आईडी";
  static const String paymentdate = "भुकतान दिनांक";
  static const String referencenumber = "रिफरेन्स नंबर";
  static const String plancost = "प्लान कॉस्ट";
  static const String elevationcost = "एलिवेशन कॉस्ट";
  static const String selectarea = "क्षेत्र का चयन करें";
  static const String selectdirection = "दिशा चुनें";
  static const String selectfloor = "फ्लोर चुने";
  static const String errormobilenumber = "मोबाइल नंबर खाली नहीं छोड़ा जा सकता";
  static const String errorpassword = "पासवर्ड खाली नहीं छोड़ा जा सकता";
  static const String errorvalidmobileno = "कृपया मान्य मोबाइल नंबर दर्ज करें";
  static const String errorname = "नाम खाली नहीं छोड़ा जा सकता";
  static const String errorlocalitycity =
      "इलाका और शहर खाली नहीं छोड़ा जा सकता";
  static const String errorconfirmpassword =
      'कन्फर्म पासवर्ड खाली नहीं छोड़ा जा सकता';
  static const String errorpassconfirmPassword =
      'पासवर्ड और कन्फर्म पासवर्ड एक होना चाहिए';
  static const String entermobilenumber = "मोबाइल नंबर दर्ज करें";
  static const String getotp = "ओटीपी प्राप्त करें";
  static const String forgotpass = "पासवर्ड भूल गए";
  static const String erroraddress = "पता खाली नहीं छोड़ा जा सकता";
  static const String currentnothingtoshow =
      "वर्तमान में, दिखाने के लिए कुछ भी नहीं है";
  static const String enterlength = "कृपया लंबाई दर्ज करें";
  static const String errorlength = "कृपया मान्य लंबाई दर्ज करें";
  static const String errorwidth = "कृपया मान्य चौड़ाई दर्ज करें";
  static const String entyerwidth = "कृपया चौड़ाई दर्ज करें";
  static const String enterfacingdirection = "कृपया दिशा चुनें";
  static const String enterplanfloor = "कृपया योजना तल का चयन करें";
  static const String enterelevation = "कृपया एलिवेशन चुनें";
  static const String lengthbetween1 = "कृपया ";
  static const String to = " से ";
  static const String lengthbetween2 = " के बीच की लंबाई निर्दिष्ट करें ";
  static const String widthbetween1 = "कृपया ";
  static const String widthbetween2 = " के बीच की चौड़ाई निर्दिष्ट करें ";
}

class CustomFontFamily {
  CustomFontFamily._();

  static const String robotoRegular = 'assets/font/Roboto-Regular.ttf';
  static const String robotoBold = 'assets/font/Roboto-Bold.ttf';
}
